// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfjcL_3_0867TEMn6KIAJblGEeItQIEQE',
    appId: '1:208883840983:web:710c6dc2736f9773273d92',
    messagingSenderId: '208883840983',
    projectId: 'bookkaroo-747a6',
    authDomain: 'bookkaroo-747a6.firebaseapp.com',
    storageBucket: 'bookkaroo-747a6.appspot.com',
    measurementId: 'G-EH7TKRNCBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOxi9puYntUTRen1Zf4TR9sl8OzjmGlM',
    appId: '1:208883840983:android:99fcd00933a70459273d92',
    messagingSenderId: '208883840983',
    projectId: 'bookkaroo-747a6',
    storageBucket: 'bookkaroo-747a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuziN5C-pkbfITcAtrkmgCSEz7xqqNt5s',
    appId: '1:208883840983:ios:683258c6b0ad8bdc273d92',
    messagingSenderId: '208883840983',
    projectId: 'bookkaroo-747a6',
    storageBucket: 'bookkaroo-747a6.appspot.com',
    androidClientId: '208883840983-kbpdom9pbvkr1fd7eg89ere1opf1r57r.apps.googleusercontent.com',
    iosClientId: '208883840983-97dvqm6hohk5lvtsaoobeh0v6afse6gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookkarooowner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuziN5C-pkbfITcAtrkmgCSEz7xqqNt5s',
    appId: '1:208883840983:ios:683258c6b0ad8bdc273d92',
    messagingSenderId: '208883840983',
    projectId: 'bookkaroo-747a6',
    storageBucket: 'bookkaroo-747a6.appspot.com',
    androidClientId: '208883840983-kbpdom9pbvkr1fd7eg89ere1opf1r57r.apps.googleusercontent.com',
    iosClientId: '208883840983-97dvqm6hohk5lvtsaoobeh0v6afse6gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookkarooowner',
  );
}
